export const COMPONENT_NAME = "{{ .Any.NIP_COMPONENT_NAME }}"
export const NEXUS_NAME = "{{ .Any.NIP_NEXUS_NAME }}"
export const NEXUS_URL = "{{ .Any.NIP_NEXUS_URL }}"
export const DEV_PORTAL_URL = "{{ .Any.NIP_DEV_PORTAL_URL }}"
export const OG_IMAGE = "{{ .Any.NIP_OG_IMAGE }}"
